export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum RoleLevel {
  ATTORNEY = 'ATTORNEY',
  PARALEGAL = 'PARALEGAL',
  LEGAL_ASSISTANT = 'LEGAL_ASSISTANT',
  RECEPTIONIST = 'RECEPTIONIST',
  ADMIN = 'ADMIN',
}

export enum MatterStatus {
  LEAD = 'LEAD',
  INTAKE = 'INTAKE',
  CONFLICT_CHECK = 'CONFLICT_CHECK',
  RETAINER_PENDING = 'RETAINER_PENDING',
  OPEN = 'OPEN',
  ACTIVE = 'ACTIVE',
  DISCOVERY = 'DISCOVERY',
  NEGOTIATION = 'NEGOTIATION',
  MEDIATION = 'MEDIATION',
  TRIAL_PREP = 'TRIAL_PREP',
  ON_HOLD = 'ON_HOLD',
  PENDING_CLOSE = 'PENDING_CLOSE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum DocumentLifecycle {
  DRAFT = 'DRAFT',
  GENERATING = 'GENERATING',
  GENERATED = 'GENERATED',
  INTERNAL_REVIEW = 'INTERNAL_REVIEW',
  ATTORNEY_REVIEW = 'ATTORNEY_REVIEW',
  ATTORNEY_APPROVED = 'ATTORNEY_APPROVED',
  REJECTED = 'REJECTED',
  REVISION_NEEDED = 'REVISION_NEEDED',
  SIGNED = 'SIGNED',
  FILED = 'FILED',
}

export enum FilingPacketStatus {
  ASSEMBLING = 'ASSEMBLING',
  DOCUMENTS_COMPLETE = 'DOCUMENTS_COMPLETE',
  READY_FOR_ATTORNEY_REVIEW = 'READY_FOR_ATTORNEY_REVIEW',
  ATTORNEY_APPROVED = 'ATTORNEY_APPROVED',
  ATTORNEY_REJECTED = 'ATTORNEY_REJECTED',
  SUBMITTED_TO_COURT = 'SUBMITTED_TO_COURT',
  ACCEPTED = 'ACCEPTED',
  REJECTED_BY_COURT = 'REJECTED_BY_COURT',
  DEFICIENCY_NOTICE = 'DEFICIENCY_NOTICE',
  CORRECTING = 'CORRECTING',
  ARCHIVED = 'ARCHIVED',
}

export enum ChecklistItemStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  BLOCKED = 'BLOCKED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  ATTORNEY_REVIEW = 'ATTORNEY_REVIEW',
  COMPLETED = 'COMPLETED',
  WAIVED = 'WAIVED',
  SKIPPED = 'SKIPPED',
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  QUALIFIED = 'QUALIFIED',
  CONFLICT_FLAGGED = 'CONFLICT_FLAGGED',
  CONVERTED = 'CONVERTED',
  REJECTED = 'REJECTED',
  ABANDONED = 'ABANDONED',
}

export enum PartyRole {
  PETITIONER = 'PETITIONER',
  RESPONDENT = 'RESPONDENT',
  INTERVENOR = 'INTERVENOR',
  CHILD = 'CHILD',
  WITNESS = 'WITNESS',
  EXPERT = 'EXPERT',
  MEDIATOR = 'MEDIATOR',
  AMICUS = 'AMICUS',
  AD_LITEM = 'AD_LITEM',
}

export enum AuditEventType {
  MATTER_CREATED = 'MATTER_CREATED',
  MATTER_STATUS_CHANGED = 'MATTER_STATUS_CHANGED',
  DOCUMENT_GENERATED = 'DOCUMENT_GENERATED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  FILING_PACKET_SUBMITTED = 'FILING_PACKET_SUBMITTED',
  FILING_PACKET_APPROVED = 'FILING_PACKET_APPROVED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  DATA_EXPORTED = 'DATA_EXPORTED',
}

export enum MatterSensitivity {
  STANDARD = 'STANDARD',
  RESTRICTED = 'RESTRICTED',
  ACP_PROTECTED = 'ACP_PROTECTED',
  SEALED = 'SEALED',
  JUVENILE = 'JUVENILE',
}
